# Generated by Django 4.1 on 2022-09-11 16:54

from django.db import migrations, models
import django.db.models.deletion
import uuid
import vendas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('produtos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('numero', models.IntegerField(default=vendas.models.contador, editable=False, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='empresas.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='empresas.empresa')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='empresas.funcionario')),
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='VendaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_produto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendaitens', to='produtos.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendaitens', to='vendas.venda')),
            ],
        ),
    ]
