# Generated by Django 4.1 on 2022-09-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendaItens',
            new_name='VendaItem',
        ),
    ]
