# Generated by Django 4.1 on 2022-08-11 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
                ('descricao', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FaixaEtaria',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('faixa', models.CharField(max_length=256)),
                ('descricao', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'faixa etária',
                'verbose_name_plural': 'faixas etárias',
                'ordering': ['faixa'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
                ('descricao', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'gênero',
                'verbose_name_plural': 'gêneros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
                ('descricao', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'plataformas',
                'verbose_name_plural': 'plataformas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descricao', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'preço',
                'verbose_name_plural': 'preços',
                'ordering': ['data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
                ('descricao', models.TextField()),
                ('imagem', models.FileField(upload_to='media')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('estoque', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.categoria')),
                ('faixa_etaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.faixaetaria')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.genero')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.plataforma')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['nome'],
            },
        ),
    ]
