# Generated by Django 4.1 on 2022-08-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_categoria_id_alter_faixaetaria_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
