# Generated by Django 4.1 on 2022-10-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usuario_is_active_alter_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='qtd_vendas',
            field=models.IntegerField(default=0),
        ),
    ]
