# Generated by Django 4.1 on 2022-10-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_produto_qtd_vendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='comissao',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=2),
        ),
    ]
