# Generated by Django 4.1 on 2022-10-13 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_vendaitem_valor_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='preco',
            name='produto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='app.produto'),
            preserve_default=False,
        ),
    ]
