# Generated by Django 4.1 on 2022-11-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_funcionario_cargo_delete_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='comissao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
