name: Docker Push to Dockerhub

on:
  push:
    branches: [branch-docker]
  pull_request:
    branches: [branch-docker]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Tag and push image
      env:
        REGISTRY: ifscpi
        REPOSITORY: api
        IMAGE_TAG: prod-${{ github.run_number }}
        DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_REPO }}
        DOCKER_HUB_PASS: ${{ secrets.DOCKER_HUB_PASS }}
      run: |
        docker login -u $DOCKER_HUB_REPO -p $DOCKER_HUB_PASS
        docker build -t pi . --tag $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
