name: Docker Push to Dockerhub

on:

  push:
    branches: [branch-docker]

  pull_request:
    branches: [branch-docker]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Tag and push image
      env:
        REGISTRY: ifscpi
        REPOSITORY: pi
        IMAGE_TAG: prod-${{ github.run_number }}
      run: |
        docker build -t pi_api . --tag $IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$REGISTRY/$REPOSITORY:$IMAGE_TAG"