# Generated by Django 4.1 on 2022-08-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='nome_usuario',
            new_name='username',
        ),
    ]
