# Generated by Django 4.1 on 2022-08-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_nome_usuario_funcionario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
