# Generated by Django 4.1 on 2022-08-25 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_funcionario_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'funcionario', 'verbose_name_plural': 'funcionarios'},
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='data de entrada'),
        ),
    ]
